import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
@Component({ selector: 'app-material-dashboard', imports: [CommonModule, FormsModule], templateUrl: './material-dashboard.html', styleUrl: './material-dashboard.css' })
export class MaterialDashboard {
  menuOpen = false; selectedPeriod = 'This Week'; modalTitle = ''; modalMessage = '';
  readonly dates = ['09 Aug','10 Aug','11 Aug','12 Aug','13 Aug','14 Aug','15 Aug','16 Aug'];
  readonly categories = [{name:'Cement',amount:28,color:'#1d70df'},{name:'Steel',amount:22,color:'#23a56c'},{name:'Bricks',amount:16,color:'#ffae00'},{name:'Sand',amount:12,color:'#9357cf'},{name:'Concrete',amount:10,color:'#18acc2'},{name:'Electrical Materials',amount:7,color:'#ff8129'},{name:'Plumbing Materials',amount:5,color:'#f25576'}];
  readonly requests = [['MR-2026-018','Cement (OPC)','Residential Complex','Amit Sharma','200 Bags','18 Aug 2026','Pending'],['MR-2026-017','Steel (TMT 12mm)','Office Building','Rohit Verma','500 Kg','17 Aug 2026','Approved'],['MR-2026-016','Bricks','Commercial Plaza','Neha Patel','10,000 Nos','16 Aug 2026','Pending'],['MR-2026-015','Sand','Residential Complex','Amit Sharma','5 Cubic Meter','15 Aug 2026','Delivered'],['MR-2026-014','Electrical Wire','Office Building','Rohit Verma','300 Meter','14 Aug 2026','Approved']];
  readonly lowStock = [['Cement (OPC)','45 Bags','100 Bags'],['Steel (TMT 12mm)','120 Kg','300 Kg'],['Electrical Wire','50 Meter','100 Meter'],['PVC Pipes','30 Meter','80 Meter'],['Sand','2 Cubic Meter','5 Cubic Meter']];
  readonly procurement = [['PO-2026-043','Cement (OPC)','Shree Cement Ltd.','1,000 Bags','\u20B9420.00','\u20B94,20,000.00','08 Aug 2026','Received'],['PO-2026-042','Steel (TMT 12mm)','Tata Steel','2,000 Kg','\u20B958.00','\u20B91,16,000.00','07 Aug 2026','Received'],['PO-2026-041','Bricks','Local Supplier','20,000 Nos','\u20B97.50','\u20B91,50,000.00','06 Aug 2026','In Transit'],['PO-2026-040','Sand','Shree Ram Traders','10 Cubic Meter','\u20B91,200.00','\u20B912,000.00','05 Aug 2026','Pending']];
  toggleMenu(){this.menuOpen=!this.menuOpen;} periodChanged(){this.modalTitle='Dashboard updated';this.modalMessage=`Showing stock trends for ${this.selectedPeriod.toLowerCase()}.`;} viewRequest(row:string[]){this.modalTitle=row[0];this.modalMessage=`${row[1]} - ${row[4]} requested by ${row[3]} for ${row[2]}. Required by ${row[5]}.`;} showLowStock(){this.modalTitle='Low Stock Alerts';this.modalMessage=`${this.lowStock.length} materials require replenishment. Review their current and minimum stock levels.`;} showPending(){this.modalTitle='Pending Requests';this.modalMessage='18 material requests are waiting for review and approval.';} showAll(title:string){this.modalTitle=title;this.modalMessage='The complete list will be available in the respective management module.';} closeModal(){this.modalTitle='';this.modalMessage='';} exportReport(){const csv=['Request ID,Material,Project,Status',...this.requests.map(r=>[r[0],r[1],r[2],r[6]].join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='material-dashboard-report.csv';a.click();URL.revokeObjectURL(url);}
}
