from datetime import datetime

from sqlalchemy import Column, DateTime, Integer, String

from app.database.database import Base


class Notification(Base):
    """In-app notification generated by BuildTrack modules.

    The original project stored only a title/message/recipient.  Module 8 also
    needs enough context to enforce project-aware access and let the frontend
    open the record that caused the notification.  The extra fields remain
    nullable so older SQLite/PostgreSQL data stays compatible.
    """

    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(200), nullable=False, default="Notification")
    message = Column(String(500), default="")

    # Human-readable recipient retained for backwards compatibility.  New
    # notifications prefer a user's email or a canonical role.
    recipient = Column(String(100), default="ALL")
    recipient_user_id = Column(Integer, nullable=True, index=True)

    # Module 8 metadata.
    notification_type = Column(String(50), nullable=False, default="SYSTEM", index=True)
    project_id = Column(Integer, nullable=True, index=True)
    related_entity_type = Column(String(80), nullable=True)
    related_entity_id = Column(Integer, nullable=True)
    action_url = Column(String(300), nullable=True)

    status = Column(String(50), default="Unread", index=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    read_at = Column(DateTime, nullable=True)
